name: Verification of Reusable Protocol Verification Library

on:
  push: # run this workflow on every push
  pull_request: # run this workflow on every pull_request
  merge_group: # run this workflow on every PR in the merge queue

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ghcr.io/viperproject/gobra:sha-36e39e3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Verify the entire Reusable Verification Library
        run: ./verify.sh
