name: Verification of Reusable Protocol Verification Library

on:
  push: # run this workflow on every push
  pull_request: # run this workflow on every pull_request
  merge_group: # run this workflow on every PR in the merge queue

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ghcr.io/viperproject/gobra@sha256:432559ae1ea823d612e28f7e5798f1923cf7f4e343040359575c33ae081a01d9 # Gobra commit ab5ab7f
    steps:
      - name: Install git
        run: apt-get update && apt-get install -y git

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verify the entire Reusable Verification Library
        run: ./verify.sh
